### ISSUE TITLE
Can you provide the paper titled "FairRec: Fairness Testing for Deep Recommender Systems"

### ISSUE THREAD

**Issue by DXWEIE** [Grey-z/FairRec#1]
Thank you for the coding. Where can I get the access to the full paper to have a better understanding of your novel idea?

**Comment by Grey-z** [comment]
I have updated the introduction, the preprint version of the paper is posted on arxiv and the official version will be presented at the ISSTA conference in July.

**Comment by Grey-z** [comment]
> Thank you for the coding. Where can I get the access to the full paper to have a better understanding of your novel idea?

I have updated the introduction, the preprint version of the paper is posted on arxiv and the official version will be presented at the ISSTA conference in July.
